// constants/destinations.ts
// 25+ REAL SRI LANKAN DESTINATIONS — ONLY 4 CATEGORIES: Beaches, Mountains, Nature, Cities
// ALL PEXELS IMAGES — 100% WORKING — READY FOR SUBMISSION

export const destinations = [
  // ==================== CITIES ====================
  {
    id: 'city1',
    name: 'Colombo',
    location: 'Western Province',
    country: 'Sri Lanka',
    description: 'Vibrant capital with colonial buildings & modern skyline',
    longDescription: 'The commercial heart of Sri Lanka featuring Galle Face Green, Pettah Market, Lotus Tower and colonial architecture.',
    rating: 4.5,
    reviews: 8900,
    image: 'https://images.pexels.com/photos/30379285/pexels-photo-30379285.jpeg',
    gallery: [
      'https://images.pexels.com/photos/2547175/pexels-photo-2547175.jpeg',
      'https://images.pexels.com/photos/34843421/pexels-photo-34843421.jpeg',
    ],
    badge: 'Urban',
    category: 'Cities',
  },
  {
    id: 'city2',
    name: 'Kandy',
    location: 'Central Province',
    country: 'Sri Lanka',
    description: 'Cultural capital & home to Temple of the Tooth',
    rating: 4.8,
    reviews: 15800,
    image: 'https://images.pexels.com/photos/14041994/pexels-photo-14041994.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop',
    badge: 'Cultural',
    category: 'Cities',
  },
  {
    id: 'city3',
    name: 'Galle',
    location: 'Southern Province',
    country: 'Sri Lanka',
    description: 'Historic fort city with Dutch colonial charm',
    rating: 4.8,
    reviews: 13200,
    image: 'https://images.pexels.com/photos/2933943/pexels-photo-2933943.jpeg',
    badge: 'Heritage',
    category: 'Cities',
  },
  {
    id: 'city4',
    name: 'Jaffna',
    location: 'Northern Province',
    country: 'Sri Lanka',
    description: 'Tamil cultural hub with ancient temples',
    rating: 4.6,
    reviews: 6200,
    image: 'https://images.pexels.com/photos/6140563/pexels-photo-6140563.jpeg',
    badge: 'Cultural',
    category: 'Cities',
  },
  {
    id: 'city5',
    name: 'Anuradhapura',
    location: 'North Central Province',
    country: 'Sri Lanka',
    description: 'Ancient capital with sacred Bodhi Tree & ruins',
    longDescription: 'UNESCO World Heritage Site and ancient capital of Sri Lanka, home to the sacred Sri Maha Bodhi tree and magnificent stupas.',
    rating: 4.7,
    reviews: 12400,
    image: 'https://images.pexels.com/photos/13667947/pexels-photo-13667947.jpeg',
    gallery: [
      'https://images.pexels.com/photos/13667946/pexels-photo-13667946.jpeg',
    ],
    badge: 'Ancient',
    category: 'Cities',
  },
  {
    id: 'city6',
    name: 'Polonnaruwa',
    location: 'North Central Province',
    country: 'Sri Lanka',
    description: 'Medieval capital with stone carvings & palaces',
    longDescription: 'UNESCO World Heritage Site featuring the ancient city of Polonnaruwa with its magnificent stone carvings, palaces, and irrigation systems.',
    rating: 4.8,
    reviews: 9800,
    image: 'https://images.pexels.com/photos/13764965/pexels-photo-13764965.jpeg',
    gallery: [
      'https://images.pexels.com/photos/12584869/pexels-photo-12584869.jpeg',
    ],
    badge: 'Heritage',
    category: 'Cities',
  },
  {
    id: 'city7',
    name: 'Ella',
    location: 'Uva Province',
    country: 'Sri Lanka',
    description: 'Charming hill town with Nine Arch Bridge',
    longDescription: 'Laid-back hill town surrounded by tea plantations and the iconic Nine Arch Bridge. Perfect base for hiking and enjoying misty mountain views.',
    rating: 4.9,
    reviews: 19800,
    image: 'https://images.pexels.com/photos/12147639/pexels-photo-12147639.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop',
    badge: 'Trending',
    category: 'Cities',
  },
  {
    id: 'city8',
    name: 'Nuwara Eliya',
    location: 'Central Province',
    country: 'Sri Lanka',
    description: 'Tea country town with cool mountain climate',
    longDescription: 'Known as "Little England", this charming hill town features colonial architecture, tea plantations, and cooler temperatures.',
    rating: 4.8,
    reviews: 16800,
    image: 'https://images.pexels.com/photos/756022/pexels-photo-756022.jpeg',
    badge: 'Tea Country',
    category: 'Cities',
  },
  {
    id: 'city9',
    name: 'Haputale',
    location: 'Uva Province',
    country: 'Sri Lanka',
    description: 'Scenic town with Lipton\'s Seat viewpoint',
    longDescription: 'Peaceful hill town offering stunning views and access to Lipton\'s Seat, where Sir Thomas Lipton surveyed his tea empire.',
    rating: 4.8,
    reviews: 9200,
    image: 'https://images.pexels.com/photos/32414361/pexels-photo-32414361.jpeg',
    badge: 'Scenic',
    category: 'Cities',
  },

  // ==================== BEACHES ====================
  {
    id: 'beach1',
    name: 'Mirissa Beach',
    location: 'Southern Province',
    country: 'Sri Lanka',
    description: 'Whale watching paradise & golden sands',
    longDescription: 'Famous for whale & dolphin tours, rope swings and the best coconut cocktails in Sri Lanka.',
    rating: 4.9,
    reviews: 18200,
    image: 'https://images.pexels.com/photos/1005417/pexels-photo-1005417.jpeg',
    badge: 'Popular',
    category: 'Beaches',
  },
  {
    id: 'beach2',
    name: 'Unawatuna Beach',
    location: 'Southern Province',
    country: 'Sri Lanka',
    description: 'Calm bay with coral reefs & turtles',
    longDescription: 'Protected bay perfect for swimming and snorkeling, with coral gardens and occasional turtle sightings.',
    rating: 4.8,
    reviews: 15600,
    image: 'https://images.pexels.com/photos/319930/pexels-photo-319930.jpeg',
    badge: 'Relaxing',
    category: 'Beaches',
  },
  {
    id: 'beach3',
    name: 'Arugam Bay',
    location: 'Eastern Province',
    country: 'Sri Lanka',
    description: 'World-class surfing & laid-back vibes',
    longDescription: 'Famous for its consistent waves and laid-back surfer culture. Also known for whale watching and stargazing.',
    rating: 4.8,
    reviews: 9800,
    image: 'https://images.pexels.com/photos/1998439/pexels-photo-1998439.jpeg',
    badge: 'Surfing',
    category: 'Beaches',
  },
  {
    id: 'beach4',
    name: 'Bentota Beach',
    location: 'Western Province',
    country: 'Sri Lanka',
    description: 'Wide golden beach with water sports',
    longDescription: 'Popular beach destination offering water sports, river safaris, and luxury resorts along the southwest coast.',
    rating: 4.7,
    reviews: 11200,
    image: 'https://images.pexels.com/photos/16946715/pexels-photo-16946715.jpeg',
    badge: 'Family',
    category: 'Beaches',
  },
  {
    id: 'beach5',
    name: 'Hikkaduwa Beach',
    location: 'Southern Province',
    country: 'Sri Lanka',
    description: 'Coral gardens & vibrant nightlife',
    longDescription: 'Known for its coral sanctuary and vibrant beach scene with bars, restaurants, and water sports.',
    rating: 4.7,
    reviews: 8900,
    image: 'https://images.pexels.com/photos/12548554/pexels-photo-12548554.jpeg',
    badge: 'Party',
    category: 'Beaches',
  },

  // ==================== MOUNTAINS ====================
  {
    id: 'mount1',
    name: 'Ella Rock',
    location: 'Uva Province',
    country: 'Sri Lanka',
    description: 'Iconic hike with 360° views of Ella Gap',
    longDescription: 'One of the most popular hikes in Sri Lanka. The trail passes through tea plantations and ends with breathtaking panoramic views of Little Adam\'s Peak and the valley below.',
    rating: 4.9,
    reviews: 18400,
    image: 'https://images.pexels.com/photos/12147639/pexels-photo-12147639.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop',
    badge: 'Most Popular Hike',
    category: 'Mountains',
  },
  {
    id: 'mount2',
    name: 'Little Adam\'s Peak',
    location: 'Ella, Uva Province',
    country: 'Sri Lanka',
    description: 'Easy hike with stunning sunrise views',
    longDescription: 'Shorter and easier than Adam\'s Peak, perfect for beginners. Offers the same dramatic views of misty mountains and tea estates.',
    rating: 4.8,
    reviews: 16200,
    image: 'https://images.pexels.com/photos/31001499/pexels-photo-31001499.jpeg',
    badge: 'Beginner Friendly',
    category: 'Mountains',
  },
  {
    id: 'mount3',
    name: 'Adam\'s Peak (Sri Pada)',
    location: 'Central Province',
    country: 'Sri Lanka',
    description: 'Sacred mountain with footprint of Buddha/Adam/Shiva',
    longDescription: 'Pilgrimage site climbed by thousands at night to witness the spectacular sunrise and the sacred footprint at the summit.',
    rating: 5.0,
    reviews: 21300,
    image: 'https://images.pexels.com/photos/11736949/pexels-photo-11736949.jpeg',
    badge: 'Spiritual Journey',
    category: 'Mountains',
  },
  {
    id: 'mount4',
    name: 'Pidurangala Rock',
    location: 'Central Province',
    country: 'Sri Lanka',
    description: 'Best view of Sigiriya Rock Fortress',
    longDescription: 'Less crowded alternative to Sigiriya. Climb to the top for the most photographed view of the ancient rock fortress at sunrise.',
    rating: 4.9,
    reviews: 15700,
    image: 'https://images.pexels.com/photos/34218667/pexels-photo-34218667.jpeg',
    badge: 'Hidden Gem',
    category: 'Mountains',
  },
  {
    id: 'mount5',
    name: 'World\'s End - Horton Plains',
    location: 'Nuwara Eliya',
    country: 'Sri Lanka',
    description: '1,000m sheer drop with endless views',
    longDescription: 'A sudden drop-off offering one of the most dramatic viewpoints in Asia. Part of Horton Plains National Park with Baker\'s Falls.',
    rating: 4.9,
    reviews: 13400,
    image: 'https://images.pexels.com/photos/6031391/pexels-photo-6031391.jpeg',
    badge: 'Dramatic Views',
    category: 'Mountains',
  },
  {
    id: 'mount6',
    name: 'Lipton\'s Seat',
    location: 'Haputale',
    country: 'Sri Lanka',
    description: 'Viewpoint where Sir Thomas Lipton surveyed his tea empire',
    longDescription: 'Offers panoramic views over 7 provinces on a clear day. Surrounded by endless tea plantations.',
    rating: 4.8,
    reviews: 8900,
    image: 'https://images.pexels.com/photos/5042895/pexels-photo-5042895.jpeg',
    badge: 'Tea Country',
    category: 'Mountains',
  },
  {
    id: 'mount7',
    name: 'Bible Rock (Bathalegala)',
    location: 'Kandy District',
    country: 'Sri Lanka',
    description: 'Looks like an open Bible from a distance',
    longDescription: 'Unique flat-topped mountain popular among local hikers. Offers excellent views of the surrounding hills.',
    rating: 4.7,
    reviews: 6200,
    image: 'https://images.pexels.com/photos/34869252/pexels-photo-34869252.jpeg',
    badge: 'Local Favorite',
    category: 'Mountains',
  },
  {
    id: 'mount8',
    name: 'Hanuman Peak (Ravana Ella)',
    location: 'Ella',
    country: 'Sri Lanka',
    description: 'Linked to Ramayana legend',
    longDescription: 'Believed to be where Hanuman rested. Features a temple and great views of Ravana Falls.',
    rating: 4.7,
    reviews: 7800,
    image: 'https://images.pexels.com/photos/28773425/pexels-photo-28773425.jpeg',
    badge: 'Mythical',
    category: 'Mountains',
  },
  {
    id: 'mount9',
    name: 'Kirigalpoththa',
    location: 'Horton Plains',
    country: 'Sri Lanka',
    description: '2nd highest mountain in Sri Lanka (2,388m)',
    longDescription: 'Challenging hike through cloud forest. The highest point accessible without special permits.',
    rating: 4.9,
    reviews: 5400,
    image: 'https://images.pexels.com/photos/10825314/pexels-photo-10825314.jpeg',
    badge: 'Challenging',
    category: 'Mountains',
  },

  // ==================== NATURE ====================
  {
    id: 'nature1',
    name: 'Sigiriya Rock Fortress',
    location: 'Central Province',
    country: 'Sri Lanka',
    description: 'Ancient rock citadel & UNESCO site',
    longDescription: 'UNESCO World Heritage Site built in the 5th century. Known as the "Lion Rock", this ancient fortress features breathtaking frescoes and a palace on top with 360° jungle views.',
    rating: 5.0,
    reviews: 24800,
    image: 'https://images.pexels.com/photos/999068/pexels-photo-999068.jpeg',
    badge: 'Must-Visit',
    category: 'Nature',
  },
  {
    id: 'nature2',
    name: 'Yala National Park',
    location: 'Southern Province',
    country: 'Sri Lanka',
    description: 'Highest leopard density in the world',
    longDescription: 'Famous for its high concentration of leopards, elephants, and diverse wildlife. One of the best safari destinations in Asia.',
    rating: 4.9,
    reviews: 18900,
    image: 'https://images.pexels.com/photos/33130315/pexels-photo-33130315.jpeg',
    badge: 'Wildlife',
    category: 'Nature',
  },
  {
    id: 'nature3',
    name: 'Sinharaja Rainforest',
    location: 'Southern Province',
    country: 'Sri Lanka',
    description: 'UNESCO biodiversity hotspot',
    longDescription: 'One of the last remaining primary tropical rainforests in Sri Lanka, home to over 60% of the country\'s endemic species.',
    rating: 4.9,
    reviews: 9800,
    image: 'https://images.pexels.com/photos/34855023/pexels-photo-34855023.jpeg',
    badge: 'Rainforest',
    category: 'Nature',
  },
  {
    id: 'nature4',
    name: 'Udawalawe National Park',
    location: 'Southern Province',
    country: 'Sri Lanka',
    description: 'Hundreds of wild elephants',
    longDescription: 'Known for its large elephant population and the Udawalawe Reservoir. Excellent for wildlife viewing and photography.',
    rating: 4.8,
    reviews: 13200,
    image: 'https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&fit=crop',
    badge: 'Safari',
    category: 'Nature',
  },
];